apiVersion: v1
kind: Namespace
metadata:
  name: octrix
  labels:
    app.kubernetes.io/name: octrix
    app.kubernetes.io/part-of: octrix
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: octrix
